name: Generate GitHub Streak Badge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_streak_badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Streak Badge
        uses: Platane/snk@v3
        with:
          github_user_name: FaisalSatti
          outputs: dist/streak.svg

      - name: Commit and Push the Streak Badge to Repository
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions Bot'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Update GitHub Streak badge'
          add: 'dist/streak.svg'

      - name: Push Changes to Repository
        uses: ad-m/github-push-action@v0.7  # Changed to a working version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
